[rospy.client][INFO] 2018-02-26 12:02:15,859: init_node, name[/rqt_gui_py_node_23079], pid[23079]
[xmlrpc][INFO] 2018-02-26 12:02:15,859: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-02-26 12:02:15,860: Started XML-RPC server [http://tygrys.robotyka.ia.pw.edu.pl:43317/]
[rospy.init][INFO] 2018-02-26 12:02:15,860: ROS Slave URI: [http://tygrys.robotyka.ia.pw.edu.pl:43317/]
[rospy.impl.masterslave][INFO] 2018-02-26 12:02:15,861: _ready: http://tygrys.robotyka.ia.pw.edu.pl:43317/
[rospy.registration][INFO] 2018-02-26 12:02:15,863: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2018-02-26 12:02:15,863: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2018-02-26 12:02:15,962: registered with master
[rospy.rosout][INFO] 2018-02-26 12:02:15,963: initializing /rosout core topic
[rospy.rosout][INFO] 2018-02-26 12:02:15,966: connected to core topic /rosout
[rospy.simtime][INFO] 2018-02-26 12:02:15,967: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosgraph.graph][ERROR] 2018-02-26 12:02:16,112: cannot get stats info from node [/sim]: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/impl/graph.py", line 395, in _node_refresh_businfo
    code, msg, bus_info = api.getBusInfo(_ROS_NAME)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Połączenie odrzucone

[rospy.internal][INFO] 2018-02-26 12:02:16,266: topic[/rosout] adding connection to [/rosout], count 0
